apiVersion: v1
kind: Secret
metadata:
  name: webhook-secrets
  namespace: monitoring
type: Opaque
stringData:
  # --- JIRA ---
  JIRA_BASE_URL: "https://crcrazylearning.atlassian.net/"
  JIRA_PROJECT_KEY: "SRE_OPS"
  JIRA_EMAIL: "cr.crazylearning@gmail.com"
  JIRA_API_TOKEN: "<YOUR_JIRA_API_TOKEN>"

  # --- Slack ---
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"

  # --- Bedrock ---
  BEDROCK_AGENT_RUNTIME_ID: "k8sAlertAgent-M0jfa63WYr"
  AWS_ACCOUNT_ID: "020930354342"
  AWS_REGION: "us-east-1"
  EKS_CLUSTER_NAME: "demo-cluster"
